version: '3.9'

services:
  php_apache:
    container_name: php_8.2_apache_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - "/var/www/html/vendor"
      - "./:/var/www/html"
      - "./vendor:/var/www/html/vendor"
    networks:
      - guviwebdev_network
    depends_on:
      - mysql
      - mongodb
      - redis

  mysql:
    image: mysql:8.1.0
    container_name: mysql_8.1.0_container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - guviwebdev_network

  redis:
    image: redis:latest
    command: [ "redis-server", "--bind", "redis", "--port", "6379" ]
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    networks:
      - guviwebdev_network

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - "./mongo:/data/db"
    networks:
      - guviwebdev_network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - guviwebdev_network

networks:
  guviwebdev_network:
